

python plot_correction_data16_13TeV_EGAM1_probes_lhmedium_JF17_vetolhvloose_with_tansig.py -i data_cern/analysis/files/data16_13TeV.EGAM1.probes_lhmedium.JF17.vetolhvloose.correction_with_tansig.root -o plot_correction_data16_13TeV_EGAM1_probes_lhmedium_JF17_vetolhvloose_with_tansig



