

python3 plot_correction_v6_data16_13TeV_EGAM1_probes_lhmedium_JF17_vetolhvloose.py -i ../phd_data/correction_v6_data16_13TeV_EGAM1_probes_lhmedium_JF17_vetolhvloose/data16_13TeV.EGAM1.probes_lhmedium.JF17.vetolhvloose.correction.root -o correction_data16_EGAM1_probes_lhmedium



