

python3 plot_correction_v8_data17_13TeV_EGAM1_probes_lhmedium_EGAM7_vetolhvloose.py -i ../phd_data/correction_v8_data17_13TeV_EGAM1_probes_lhmedium_EGAM7_vetolhvloose/data17_13TeV_EGAM1_probes_lhmedium_EGAM7_vetolhvloose.v8.correction.root -o correction_data17_EGAM1_probes_lhmedium_v8



